name: Build wiringX

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set platform env
      uses: actions/checkout@v2

    - name: Installation depends
      run: |
        echo "to prepare the env ..."
        sudo apt-get update
        echo "== install python env =="
        sudo apt-get install -y python2-dev python2.7 python-dev-is-python3 python3 python3.9
        sudo apt-get install -y git build-essential swig  libnode-dev  cmake libjson-c-dev libc6 libgcc1 libstdc++6   libgtest-dev pkg-config cmake-data
        echo "env ok ..."

    - name: Clone source code
      run: |
        echo "to get the source code !"
        git clone https://github.com/nascs/wiringX.git
        echo $PWD
        echo "WORK_DIR=$(pwd)" >> $GITHUB_ENV
        # /home/runner/work/github_action_demo/github_action_demo

    - name: Set up build env
      run: |
        cd $WORK_DIR/wiringX
        echo $WORK_DIR/wiringX
        echo "to build wiringX && PWD: $PWD"
        echo "============== $ls ==============" 
        mkdir build
        cd build
        cmake ..
      # working-directory: build

    - name: Build Project
      run: |
        make -j8
        cpack -G DEB
        echo  "============== $PWD =============="
        ls *.deb
        echo "============== Build complete =============="
      working-directory: build
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: wiringx-deb
        path: ./*.deb
