name: Build wiringX

on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set platform env
      uses: actions/checkout@v4

    - name: Installation depends
      run: |
        echo "============== to prepare the env ============== "
        sudo apt-get update -y
        sudo apt-get install -y python2-dev python2.7 python-dev-is-python3 python3 python3.9
        sudo apt-get install -y git build-essential swig  libnode-dev  cmake libjson-c-dev libc6 libgcc1 libstdc++6   libgtest-dev pkg-config cmake-data

    - name: Clone source code
      run: |
        echo "============== to get the source code ! =============="
        git clone https://github.com/nascs/wiringX.git

    - name: Set up build env
      run: |
        export CC=/usr/bin/gcc
        cd ${{ github.workspace }}/wiringX
        echo ${{ github.workspace }}/wiringX
        mkdir build
        cd build
        cmake ..

    - name: Build Project
      run: |
        cd ${{ github.workspace }}/wiringX/build
        export CC=/usr/bin/gcc
        make -j8
        cpack -G DEB
        echo "============== Build complete =============="

  Upload_artifact:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wiringx-deb
          path: ${{ github.workspace }}/wiringX/build/libwiringx*.deb
          if-no-files-found: error
