name: Build wiringX
on: 
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Installation depends
      run: |
        echo "to prepare the env ..."
        sudo apt-get update
        echo "== install python env =="
        sudo apt-get install -y python2-dev python2.7 python-dev-is-python3 python3 python3.9
        sudo apt-get install -y git build-essential swig  libnode-dev  cmake libjson-c-dev libc6 libgcc1 libstdc++6   libgtest-dev pkg-config cmake-data
        echo "env ok ..."
    - name: Clone source code
      run: |
        echo "to get the source code !"
        git clone https://github.com/nascs/wiringX.git

    - name: Build
      run: |
        echo "to build wiringX"
        cd wiringX
        mkdir build
        cd build
        cmake ..
        make -j8
        cpack -G DEB
        echo  "============== $PWD =============="
        echo "$ls"
    - name : Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: github_action_demo
        path: github_action_demo/**/*.deb


  # release:
  #   needs: build

  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: upload artifact
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: github_action_demo
  #       path: github_action_demo/**/*.deb
